"""empty message

Revision ID: 20c4319a769a
Revises: 
Create Date: 2020-03-24 09:54:20.405825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c4319a769a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('identifier', sa.String(length=256), nullable=False),
    sa.Column('tel', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('mail', sa.String(length=128), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tel'),
    sa.UniqueConstraint('username')
    )
    op.create_table('writer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('_password', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=False),
    sa.Column('mail', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('tel'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writer')
    op.drop_table('publisher')
    op.drop_table('admin')
    # ### end Alembic commands ###
