"""empty message

Revision ID: 54df9a0c415d
Revises: 
Create Date: 2020-03-23 21:20:20.602339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54df9a0c415d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('_password', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=False),
    sa.Column('mail', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writer')
    # ### end Alembic commands ###
