"""empty message

Revision ID: d5c83613bfc3
Revises: ac18b985b59f
Create Date: 2020-03-22 20:57:27.927239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c83613bfc3'
down_revision = 'ac18b985b59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'writer', ['tel'])
    op.create_unique_constraint(None, 'writer', ['mail'])
    op.create_unique_constraint(None, 'writer', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'writer', type_='unique')
    op.drop_constraint(None, 'writer', type_='unique')
    op.drop_constraint(None, 'writer', type_='unique')
    # ### end Alembic commands ###
